version: "3.3"
services:
  postgres:
    env_file:
      - ./.env
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    environment:
      - POSTGRES_DB=dailyRoutine
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "2137:5432"
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  postgres: null
